// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coverage.sql

package db

import (
	"context"
)

const deleteAlbumCoverageForLibraryAlbum = `-- name: DeleteAlbumCoverageForLibraryAlbum :exec
DELETE FROM album_coverage WHERE library_album_id = ?
`

func (q *Queries) DeleteAlbumCoverageForLibraryAlbum(ctx context.Context, libraryAlbumID string) error {
	_, err := q.db.ExecContext(ctx, deleteAlbumCoverageForLibraryAlbum, libraryAlbumID)
	return err
}

const getAlbumCoverage = `-- name: GetAlbumCoverage :one
SELECT source, external_album_id, coverage_json, library_album_id, fetched_at FROM album_coverage WHERE source = ? AND external_album_id = ?
`

type GetAlbumCoverageParams struct {
	Source          string `json:"source"`
	ExternalAlbumID string `json:"external_album_id"`
}

func (q *Queries) GetAlbumCoverage(ctx context.Context, arg GetAlbumCoverageParams) (AlbumCoverage, error) {
	row := q.db.QueryRowContext(ctx, getAlbumCoverage, arg.Source, arg.ExternalAlbumID)
	var i AlbumCoverage
	err := row.Scan(
		&i.Source,
		&i.ExternalAlbumID,
		&i.CoverageJson,
		&i.LibraryAlbumID,
		&i.FetchedAt,
	)
	return i, err
}

const getArtistExternalMap = `-- name: GetArtistExternalMap :one
SELECT library_artist_id, source, external_artist_id, confidence, created_at FROM artist_external_map WHERE library_artist_id = ? AND source = ?
`

type GetArtistExternalMapParams struct {
	LibraryArtistID string `json:"library_artist_id"`
	Source          string `json:"source"`
}

func (q *Queries) GetArtistExternalMap(ctx context.Context, arg GetArtistExternalMapParams) (ArtistExternalMap, error) {
	row := q.db.QueryRowContext(ctx, getArtistExternalMap, arg.LibraryArtistID, arg.Source)
	var i ArtistExternalMap
	err := row.Scan(
		&i.LibraryArtistID,
		&i.Source,
		&i.ExternalArtistID,
		&i.Confidence,
		&i.CreatedAt,
	)
	return i, err
}

const getDiscographyCache = `-- name: GetDiscographyCache :one
SELECT source, external_artist_id, albums_json, fetched_at FROM discography_cache WHERE source = ? AND external_artist_id = ?
`

type GetDiscographyCacheParams struct {
	Source           string `json:"source"`
	ExternalArtistID string `json:"external_artist_id"`
}

func (q *Queries) GetDiscographyCache(ctx context.Context, arg GetDiscographyCacheParams) (DiscographyCache, error) {
	row := q.db.QueryRowContext(ctx, getDiscographyCache, arg.Source, arg.ExternalArtistID)
	var i DiscographyCache
	err := row.Scan(
		&i.Source,
		&i.ExternalArtistID,
		&i.AlbumsJson,
		&i.FetchedAt,
	)
	return i, err
}

const upsertAlbumCoverage = `-- name: UpsertAlbumCoverage :exec
INSERT INTO album_coverage (source, external_album_id, coverage_json, library_album_id, fetched_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(source, external_album_id) DO UPDATE SET
  coverage_json = excluded.coverage_json, library_album_id = excluded.library_album_id, fetched_at = excluded.fetched_at
`

type UpsertAlbumCoverageParams struct {
	Source          string `json:"source"`
	ExternalAlbumID string `json:"external_album_id"`
	CoverageJson    string `json:"coverage_json"`
	LibraryAlbumID  string `json:"library_album_id"`
	FetchedAt       int64  `json:"fetched_at"`
}

func (q *Queries) UpsertAlbumCoverage(ctx context.Context, arg UpsertAlbumCoverageParams) error {
	_, err := q.db.ExecContext(ctx, upsertAlbumCoverage,
		arg.Source,
		arg.ExternalAlbumID,
		arg.CoverageJson,
		arg.LibraryAlbumID,
		arg.FetchedAt,
	)
	return err
}

const upsertArtistExternalMap = `-- name: UpsertArtistExternalMap :exec
INSERT INTO artist_external_map (library_artist_id, source, external_artist_id, confidence, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(library_artist_id, source) DO UPDATE SET
  external_artist_id = excluded.external_artist_id, confidence = excluded.confidence
`

type UpsertArtistExternalMapParams struct {
	LibraryArtistID  string  `json:"library_artist_id"`
	Source           string  `json:"source"`
	ExternalArtistID string  `json:"external_artist_id"`
	Confidence       float64 `json:"confidence"`
	CreatedAt        int64   `json:"created_at"`
}

func (q *Queries) UpsertArtistExternalMap(ctx context.Context, arg UpsertArtistExternalMapParams) error {
	_, err := q.db.ExecContext(ctx, upsertArtistExternalMap,
		arg.LibraryArtistID,
		arg.Source,
		arg.ExternalArtistID,
		arg.Confidence,
		arg.CreatedAt,
	)
	return err
}

const upsertDiscographyCache = `-- name: UpsertDiscographyCache :exec
INSERT INTO discography_cache (source, external_artist_id, albums_json, fetched_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(source, external_artist_id) DO UPDATE SET
  albums_json = excluded.albums_json, fetched_at = excluded.fetched_at
`

type UpsertDiscographyCacheParams struct {
	Source           string `json:"source"`
	ExternalArtistID string `json:"external_artist_id"`
	AlbumsJson       string `json:"albums_json"`
	FetchedAt        int64  `json:"fetched_at"`
}

func (q *Queries) UpsertDiscographyCache(ctx context.Context, arg UpsertDiscographyCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscographyCache,
		arg.Source,
		arg.ExternalArtistID,
		arg.AlbumsJson,
		arg.FetchedAt,
	)
	return err
}
