// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"
	"database/sql"
)

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (id, code, role_id, created_by, expires_at) VALUES (?, ?, ?, ?, ?)
`

type CreateInviteParams struct {
	ID        string         `json:"id"`
	Code      string         `json:"code"`
	RoleID    sql.NullString `json:"role_id"`
	CreatedBy sql.NullString `json:"created_by"`
	ExpiresAt sql.NullInt64  `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.ExecContext(ctx, createInvite,
		arg.ID,
		arg.Code,
		arg.RoleID,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	return err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE id = ?
`

func (q *Queries) DeleteInvite(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteInvite, id)
	return err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT id, code, role_id, created_by, expires_at, used_by, used_at, created_at FROM invites WHERE code = ?
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getInviteByCode, code)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.RoleID,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT id, code, role_id, created_by, expires_at, used_by, used_at, created_at FROM invites ORDER BY created_at DESC
`

func (q *Queries) ListInvites(ctx context.Context) ([]Invite, error) {
	rows, err := q.db.QueryContext(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.RoleID,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.UsedBy,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteUsed = `-- name: MarkInviteUsed :exec
UPDATE invites SET used_by = ?, used_at = unixepoch() WHERE id = ?
`

type MarkInviteUsedParams struct {
	UsedBy sql.NullString `json:"used_by"`
	ID     string         `json:"id"`
}

func (q *Queries) MarkInviteUsed(ctx context.Context, arg MarkInviteUsedParams) error {
	_, err := q.db.ExecContext(ctx, markInviteUsed, arg.UsedBy, arg.ID)
	return err
}
