// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type AdapterInstance struct {
	ID         string `json:"id"`
	Type       string `json:"type"`
	Name       string `json:"name"`
	Enabled    int64  `json:"enabled"`
	Priority   int64  `json:"priority"`
	ConfigJson string `json:"config_json"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

type AlbumCoverage struct {
	Source          string `json:"source"`
	ExternalAlbumID string `json:"external_album_id"`
	CoverageJson    string `json:"coverage_json"`
	LibraryAlbumID  string `json:"library_album_id"`
	FetchedAt       int64  `json:"fetched_at"`
}

type ArtistExternalMap struct {
	LibraryArtistID  string  `json:"library_artist_id"`
	Source           string  `json:"source"`
	ExternalArtistID string  `json:"external_artist_id"`
	Confidence       float64 `json:"confidence"`
	CreatedAt        int64   `json:"created_at"`
}

type DiscographyCache struct {
	Source           string `json:"source"`
	ExternalArtistID string `json:"external_artist_id"`
	AlbumsJson       string `json:"albums_json"`
	FetchedAt        int64  `json:"fetched_at"`
}

type DownloadJob struct {
	ID             string         `json:"id"`
	DedupKey       string         `json:"dedup_key"`
	RequestJson    string         `json:"request_json"`
	DownloaderName string         `json:"downloader_name"`
	Status         string         `json:"status"`
	Progress       int64          `json:"progress"`
	Error          string         `json:"error"`
	OutputPath     string         `json:"output_path"`
	LibraryTrackID sql.NullString `json:"library_track_id"`
	Priority       int64          `json:"priority"`
	RequestedBy    sql.NullString `json:"requested_by"`
	Attempts       int64          `json:"attempts"`
	CreatedAt      int64          `json:"created_at"`
	StartedAt      sql.NullInt64  `json:"started_at"`
	FinishedAt     sql.NullInt64  `json:"finished_at"`
}

type MatchCache struct {
	Source         string         `json:"source"`
	ExternalID     string         `json:"external_id"`
	LibraryTrackID sql.NullString `json:"library_track_id"`
	Method         string         `json:"method"`
	Confidence     float64        `json:"confidence"`
	Isrc           string         `json:"isrc"`
	Mbid           string         `json:"mbid"`
	DurationMs     int64          `json:"duration_ms"`
	LibraryVersion int64          `json:"library_version"`
	MatchedAt      int64          `json:"matched_at"`
}

type Session struct {
	ID        string `json:"id"`
	TokenHash string `json:"token_hash"`
	CreatedAt int64  `json:"created_at"`
	ExpiresAt int64  `json:"expires_at"`
	LastSeen  int64  `json:"last_seen"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}
