// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type AdapterInstance struct {
	ID         string `json:"id"`
	Type       string `json:"type"`
	Name       string `json:"name"`
	Enabled    int64  `json:"enabled"`
	Priority   int64  `json:"priority"`
	ConfigJson string `json:"config_json"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

type AlbumCoverage struct {
	Source          string `json:"source"`
	ExternalAlbumID string `json:"external_album_id"`
	CoverageJson    string `json:"coverage_json"`
	LibraryAlbumID  string `json:"library_album_id"`
	FetchedAt       int64  `json:"fetched_at"`
	LibraryVersion  int64  `json:"library_version"`
}

type AlbumExternalMap struct {
	LibraryAlbumID  string  `json:"library_album_id"`
	Source          string  `json:"source"`
	ExternalAlbumID string  `json:"external_album_id"`
	Confidence      float64 `json:"confidence"`
	CreatedAt       int64   `json:"created_at"`
}

type ArtistExternalMap struct {
	LibraryArtistID  string  `json:"library_artist_id"`
	Source           string  `json:"source"`
	ExternalArtistID string  `json:"external_artist_id"`
	Confidence       float64 `json:"confidence"`
	CreatedAt        int64   `json:"created_at"`
}

type DiscographyCache struct {
	Source           string `json:"source"`
	ExternalArtistID string `json:"external_artist_id"`
	AlbumsJson       string `json:"albums_json"`
	FetchedAt        int64  `json:"fetched_at"`
}

type DownloadJob struct {
	ID             string         `json:"id"`
	DedupKey       string         `json:"dedup_key"`
	RequestJson    string         `json:"request_json"`
	DownloaderName string         `json:"downloader_name"`
	Status         string         `json:"status"`
	Progress       int64          `json:"progress"`
	Error          string         `json:"error"`
	OutputPath     string         `json:"output_path"`
	LibraryTrackID sql.NullString `json:"library_track_id"`
	Priority       int64          `json:"priority"`
	RequestedBy    sql.NullString `json:"requested_by"`
	Attempts       int64          `json:"attempts"`
	CreatedAt      int64          `json:"created_at"`
	StartedAt      sql.NullInt64  `json:"started_at"`
	FinishedAt     sql.NullInt64  `json:"finished_at"`
	CoverArtID     sql.NullString `json:"cover_art_id"`
	DownloaderRef  string         `json:"downloader_ref"`
	InitiatedBy    sql.NullString `json:"initiated_by"`
}

type Invite struct {
	ID        string         `json:"id"`
	Code      string         `json:"code"`
	RoleID    sql.NullString `json:"role_id"`
	CreatedBy sql.NullString `json:"created_by"`
	ExpiresAt sql.NullInt64  `json:"expires_at"`
	UsedBy    sql.NullString `json:"used_by"`
	UsedAt    sql.NullInt64  `json:"used_at"`
	CreatedAt int64          `json:"created_at"`
}

type MatchCache struct {
	Source         string         `json:"source"`
	ExternalID     string         `json:"external_id"`
	LibraryTrackID sql.NullString `json:"library_track_id"`
	Method         string         `json:"method"`
	Confidence     float64        `json:"confidence"`
	Isrc           string         `json:"isrc"`
	Mbid           string         `json:"mbid"`
	DurationMs     int64          `json:"duration_ms"`
	LibraryVersion int64          `json:"library_version"`
	MatchedAt      int64          `json:"matched_at"`
	ArtistID       string         `json:"artist_id"`
	AlbumID        string         `json:"album_id"`
	CoverArtID     string         `json:"cover_art_id"`
}

type Request struct {
	ID            string         `json:"id"`
	RequestedBy   string         `json:"requested_by"`
	Source        string         `json:"source"`
	ExternalID    string         `json:"external_id"`
	Title         string         `json:"title"`
	Artist        string         `json:"artist"`
	Album         sql.NullString `json:"album"`
	Isrc          sql.NullString `json:"isrc"`
	DurationMs    sql.NullInt64  `json:"duration_ms"`
	CoverArtID    sql.NullString `json:"cover_art_id"`
	Status        string         `json:"status"`
	CreatedAt     int64          `json:"created_at"`
	DecidedBy     sql.NullString `json:"decided_by"`
	DecidedAt     sql.NullInt64  `json:"decided_at"`
	DownloadJobID sql.NullString `json:"download_job_id"`
	DenyReason    sql.NullString `json:"deny_reason"`
	CoverUrl      sql.NullString `json:"cover_url"`
}

type Role struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	IsSystem     int64  `json:"is_system"`
	Capabilities string `json:"capabilities"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type Session struct {
	ID        string         `json:"id"`
	TokenHash string         `json:"token_hash"`
	CreatedAt int64          `json:"created_at"`
	ExpiresAt int64          `json:"expires_at"`
	LastSeen  int64          `json:"last_seen"`
	UserID    sql.NullString `json:"user_id"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SyncedPlaylist struct {
	ID              string         `json:"id"`
	Source          string         `json:"source"`
	ExternalID      string         `json:"external_id"`
	Name            string         `json:"name"`
	CoverUrl        string         `json:"cover_url"`
	TracksJson      string         `json:"tracks_json"`
	SyncEnabled     int64          `json:"sync_enabled"`
	SyncIntervalSec int64          `json:"sync_interval_sec"`
	AutoDownload    int64          `json:"auto_download"`
	LastSyncedAt    int64          `json:"last_synced_at"`
	CreatedAt       int64          `json:"created_at"`
	Mode            string         `json:"mode"`
	OwnerUserID     sql.NullString `json:"owner_user_id"`
}

type User struct {
	ID           string        `json:"id"`
	Username     string        `json:"username"`
	PasswordHash string        `json:"password_hash"`
	RoleID       string        `json:"role_id"`
	IsOwner      int64         `json:"is_owner"`
	Disabled     int64         `json:"disabled"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
	LastSeen     sql.NullInt64 `json:"last_seen"`
}
