// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const countUnreadForUser = `-- name: CountUnreadForUser :one
SELECT COUNT(*) FROM notifications
WHERE user_id = ? AND read = 0
`

func (q *Queries) CountUnreadForUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (id, user_id, type, title, body, request_id, read, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateNotificationParams struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	Type      string         `json:"type"`
	Title     string         `json:"title"`
	Body      string         `json:"body"`
	RequestID sql.NullString `json:"request_id"`
	Read      int64          `json:"read"`
	CreatedAt int64          `json:"created_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.RequestID,
		arg.Read,
		arg.CreatedAt,
	)
	return err
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, user_id, type, title, body, request_id, read, created_at FROM notifications
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListNotificationsForUserParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.RequestID,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllReadForUser = `-- name: MarkAllReadForUser :exec
UPDATE notifications SET read = 1 WHERE user_id = ?
`

func (q *Queries) MarkAllReadForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, markAllReadForUser, userID)
	return err
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notifications SET read = 1
WHERE user_id = ? AND id IN (/*SLICE:ids*/?)
`

type MarkNotificationsReadParams struct {
	UserID string   `json:"user_id"`
	Ids    []string `json:"ids"`
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error {
	query := markNotificationsRead
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const markPendingResolvedForRequest = `-- name: MarkPendingResolvedForRequest :exec
UPDATE notifications SET read = 1
WHERE request_id = ? AND type = 'request_pending'
`

func (q *Queries) MarkPendingResolvedForRequest(ctx context.Context, requestID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, markPendingResolvedForRequest, requestID)
	return err
}
