// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plays.sql

package db

import (
	"context"
)

const insertPlay = `-- name: InsertPlay :exec
INSERT INTO plays (id, user_id, catalog_id, played_at, ms_played, completed, created_at)
VALUES (?,?,?,?,?,?,?)
`

type InsertPlayParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	CatalogID string `json:"catalog_id"`
	PlayedAt  int64  `json:"played_at"`
	MsPlayed  int64  `json:"ms_played"`
	Completed int64  `json:"completed"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) InsertPlay(ctx context.Context, arg InsertPlayParams) error {
	_, err := q.db.ExecContext(ctx, insertPlay,
		arg.ID,
		arg.UserID,
		arg.CatalogID,
		arg.PlayedAt,
		arg.MsPlayed,
		arg.Completed,
		arg.CreatedAt,
	)
	return err
}

const listRecentPlays = `-- name: ListRecentPlays :many
SELECT p.id, p.catalog_id, p.played_at, e.title, e.artist, e.album
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND p.played_at < ?
ORDER BY p.played_at DESC LIMIT ?
`

type ListRecentPlaysParams struct {
	UserID   string `json:"user_id"`
	PlayedAt int64  `json:"played_at"`
	Limit    int64  `json:"limit"`
}

type ListRecentPlaysRow struct {
	ID        string `json:"id"`
	CatalogID string `json:"catalog_id"`
	PlayedAt  int64  `json:"played_at"`
	Title     string `json:"title"`
	Artist    string `json:"artist"`
	Album     string `json:"album"`
}

func (q *Queries) ListRecentPlays(ctx context.Context, arg ListRecentPlaysParams) ([]ListRecentPlaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPlays, arg.UserID, arg.PlayedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentPlaysRow
	for rows.Next() {
		var i ListRecentPlaysRow
		if err := rows.Scan(
			&i.ID,
			&i.CatalogID,
			&i.PlayedAt,
			&i.Title,
			&i.Artist,
			&i.Album,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repointPlays = `-- name: RepointPlays :exec
UPDATE plays SET catalog_id = ? WHERE catalog_id = ?
`

type RepointPlaysParams struct {
	CatalogID   string `json:"catalog_id"`
	CatalogID_2 string `json:"catalog_id_2"`
}

func (q *Queries) RepointPlays(ctx context.Context, arg RepointPlaysParams) error {
	_, err := q.db.ExecContext(ctx, repointPlays, arg.CatalogID, arg.CatalogID_2)
	return err
}
