// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package db

import (
	"context"
	"database/sql"
)

const createRequest = `-- name: CreateRequest :exec
INSERT INTO requests (id, requested_by, source, external_id, title, artist, album, isrc, duration_ms, cover_art_id, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRequestParams struct {
	ID          string         `json:"id"`
	RequestedBy string         `json:"requested_by"`
	Source      string         `json:"source"`
	ExternalID  string         `json:"external_id"`
	Title       string         `json:"title"`
	Artist      string         `json:"artist"`
	Album       sql.NullString `json:"album"`
	Isrc        sql.NullString `json:"isrc"`
	DurationMs  sql.NullInt64  `json:"duration_ms"`
	CoverArtID  sql.NullString `json:"cover_art_id"`
	Status      string         `json:"status"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) error {
	_, err := q.db.ExecContext(ctx, createRequest,
		arg.ID,
		arg.RequestedBy,
		arg.Source,
		arg.ExternalID,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.Isrc,
		arg.DurationMs,
		arg.CoverArtID,
		arg.Status,
	)
	return err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM requests WHERE id = ?
`

func (q *Queries) DeleteRequest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRequest, id)
	return err
}

const getOpenRequestByItem = `-- name: GetOpenRequestByItem :one
SELECT id, requested_by, source, external_id, title, artist, album, isrc, duration_ms, cover_art_id, status, created_at, decided_by, decided_at, download_job_id, deny_reason FROM requests WHERE requested_by = ? AND source = ? AND external_id = ? AND status IN ('pending','approved') LIMIT 1
`

type GetOpenRequestByItemParams struct {
	RequestedBy string `json:"requested_by"`
	Source      string `json:"source"`
	ExternalID  string `json:"external_id"`
}

func (q *Queries) GetOpenRequestByItem(ctx context.Context, arg GetOpenRequestByItemParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, getOpenRequestByItem, arg.RequestedBy, arg.Source, arg.ExternalID)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.Isrc,
		&i.DurationMs,
		&i.CoverArtID,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DownloadJobID,
		&i.DenyReason,
	)
	return i, err
}

const getRequest = `-- name: GetRequest :one
SELECT id, requested_by, source, external_id, title, artist, album, isrc, duration_ms, cover_art_id, status, created_at, decided_by, decided_at, download_job_id, deny_reason FROM requests WHERE id = ?
`

func (q *Queries) GetRequest(ctx context.Context, id string) (Request, error) {
	row := q.db.QueryRowContext(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.Isrc,
		&i.DurationMs,
		&i.CoverArtID,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DownloadJobID,
		&i.DenyReason,
	)
	return i, err
}

const getRequestByDownloadJob = `-- name: GetRequestByDownloadJob :one
SELECT id, requested_by, source, external_id, title, artist, album, isrc, duration_ms, cover_art_id, status, created_at, decided_by, decided_at, download_job_id, deny_reason FROM requests WHERE download_job_id = ?
`

func (q *Queries) GetRequestByDownloadJob(ctx context.Context, downloadJobID sql.NullString) (Request, error) {
	row := q.db.QueryRowContext(ctx, getRequestByDownloadJob, downloadJobID)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.Isrc,
		&i.DurationMs,
		&i.CoverArtID,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DownloadJobID,
		&i.DenyReason,
	)
	return i, err
}

const listRequests = `-- name: ListRequests :many
SELECT id, requested_by, source, external_id, title, artist, album, isrc, duration_ms, cover_art_id, status, created_at, decided_by, decided_at, download_job_id, deny_reason FROM requests ORDER BY created_at DESC
`

func (q *Queries) ListRequests(ctx context.Context) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.RequestedBy,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Isrc,
			&i.DurationMs,
			&i.CoverArtID,
			&i.Status,
			&i.CreatedAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DownloadJobID,
			&i.DenyReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByStatus = `-- name: ListRequestsByStatus :many
SELECT id, requested_by, source, external_id, title, artist, album, isrc, duration_ms, cover_art_id, status, created_at, decided_by, decided_at, download_job_id, deny_reason FROM requests WHERE status = ? ORDER BY created_at DESC
`

func (q *Queries) ListRequestsByStatus(ctx context.Context, status string) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequestsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.RequestedBy,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Isrc,
			&i.DurationMs,
			&i.CoverArtID,
			&i.Status,
			&i.CreatedAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DownloadJobID,
			&i.DenyReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsForOwner = `-- name: ListRequestsForOwner :many
SELECT id, requested_by, source, external_id, title, artist, album, isrc, duration_ms, cover_art_id, status, created_at, decided_by, decided_at, download_job_id, deny_reason FROM requests WHERE requested_by = ? ORDER BY created_at DESC
`

func (q *Queries) ListRequestsForOwner(ctx context.Context, requestedBy string) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequestsForOwner, requestedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.RequestedBy,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Isrc,
			&i.DurationMs,
			&i.CoverArtID,
			&i.Status,
			&i.CreatedAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DownloadJobID,
			&i.DenyReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRequestStatus = `-- name: SetRequestStatus :exec
UPDATE requests SET status = ? WHERE id = ?
`

type SetRequestStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) SetRequestStatus(ctx context.Context, arg SetRequestStatusParams) error {
	_, err := q.db.ExecContext(ctx, setRequestStatus, arg.Status, arg.ID)
	return err
}

const updateRequestStatus = `-- name: UpdateRequestStatus :exec
UPDATE requests SET status = ?, decided_by = ?, decided_at = ?, download_job_id = ?, deny_reason = ? WHERE id = ?
`

type UpdateRequestStatusParams struct {
	Status        string         `json:"status"`
	DecidedBy     sql.NullString `json:"decided_by"`
	DecidedAt     sql.NullInt64  `json:"decided_at"`
	DownloadJobID sql.NullString `json:"download_job_id"`
	DenyReason    sql.NullString `json:"deny_reason"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRequestStatus,
		arg.Status,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.DownloadJobID,
		arg.DenyReason,
		arg.ID,
	)
	return err
}
