// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package db

import (
	"context"
)

const countUsersWithRole = `-- name: CountUsersWithRole :one
SELECT COUNT(*) FROM users WHERE role_id = ?
`

func (q *Queries) CountUsersWithRole(ctx context.Context, roleID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersWithRole, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (id, name, is_system, capabilities) VALUES (?, ?, ?, ?)
`

type CreateRoleParams struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	IsSystem     int64  `json:"is_system"`
	Capabilities string `json:"capabilities"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.ExecContext(ctx, createRole,
		arg.ID,
		arg.Name,
		arg.IsSystem,
		arg.Capabilities,
	)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = ?
`

func (q *Queries) DeleteRole(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const getRole = `-- name: GetRole :one
SELECT id, name, is_system, capabilities, created_at, updated_at FROM roles WHERE id = ?
`

func (q *Queries) GetRole(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsSystem,
		&i.Capabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, is_system, capabilities, created_at, updated_at FROM roles ORDER BY is_system DESC, name
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsSystem,
			&i.Capabilities,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :exec
UPDATE roles SET name = ?, capabilities = ?, updated_at = unixepoch() WHERE id = ?
`

type UpdateRoleParams struct {
	Name         string `json:"name"`
	Capabilities string `json:"capabilities"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateRole, arg.Name, arg.Capabilities, arg.ID)
	return err
}
