// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const backfillSessionUser = `-- name: BackfillSessionUser :exec
UPDATE sessions SET user_id = ? WHERE user_id IS NULL
`

func (q *Queries) BackfillSessionUser(ctx context.Context, userID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, backfillSessionUser, userID)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, token_hash, user_id, expires_at) VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string         `json:"id"`
	TokenHash string         `json:"token_hash"`
	UserID    sql.NullString `json:"user_id"`
	ExpiresAt int64          `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsForUserExcept = `-- name: DeleteSessionsForUserExcept :exec
DELETE FROM sessions WHERE user_id = ? AND token_hash <> ?
`

type DeleteSessionsForUserExceptParams struct {
	UserID    sql.NullString `json:"user_id"`
	TokenHash string         `json:"token_hash"`
}

func (q *Queries) DeleteSessionsForUserExcept(ctx context.Context, arg DeleteSessionsForUserExceptParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsForUserExcept, arg.UserID, arg.TokenHash)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, token_hash, created_at, expires_at, last_seen, user_id FROM sessions WHERE token_hash = ?
`

func (q *Queries) GetSession(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeen,
		&i.UserID,
	)
	return i, err
}
