// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: synced_playlists.sql

package db

import (
	"context"
)

const deleteSyncedPlaylist = `-- name: DeleteSyncedPlaylist :exec
DELETE FROM synced_playlists WHERE id = ?
`

func (q *Queries) DeleteSyncedPlaylist(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSyncedPlaylist, id)
	return err
}

const getSyncedPlaylist = `-- name: GetSyncedPlaylist :one
SELECT id, source, external_id, name, cover_url, tracks_json, sync_enabled, sync_interval_sec, auto_download, last_synced_at, created_at FROM synced_playlists WHERE id = ?
`

func (q *Queries) GetSyncedPlaylist(ctx context.Context, id string) (SyncedPlaylist, error) {
	row := q.db.QueryRowContext(ctx, getSyncedPlaylist, id)
	var i SyncedPlaylist
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Name,
		&i.CoverUrl,
		&i.TracksJson,
		&i.SyncEnabled,
		&i.SyncIntervalSec,
		&i.AutoDownload,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSyncedPlaylistBySource = `-- name: GetSyncedPlaylistBySource :one
SELECT id, source, external_id, name, cover_url, tracks_json, sync_enabled, sync_interval_sec, auto_download, last_synced_at, created_at FROM synced_playlists WHERE source = ? AND external_id = ?
`

type GetSyncedPlaylistBySourceParams struct {
	Source     string `json:"source"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetSyncedPlaylistBySource(ctx context.Context, arg GetSyncedPlaylistBySourceParams) (SyncedPlaylist, error) {
	row := q.db.QueryRowContext(ctx, getSyncedPlaylistBySource, arg.Source, arg.ExternalID)
	var i SyncedPlaylist
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Name,
		&i.CoverUrl,
		&i.TracksJson,
		&i.SyncEnabled,
		&i.SyncIntervalSec,
		&i.AutoDownload,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDueSyncedPlaylists = `-- name: ListDueSyncedPlaylists :many
SELECT id, source, external_id, name, cover_url, tracks_json, sync_enabled, sync_interval_sec, auto_download, last_synced_at, created_at FROM synced_playlists
WHERE sync_enabled = 1 AND sync_interval_sec > 0 AND (last_synced_at + sync_interval_sec) <= ?
`

func (q *Queries) ListDueSyncedPlaylists(ctx context.Context, lastSyncedAt int64) ([]SyncedPlaylist, error) {
	rows, err := q.db.QueryContext(ctx, listDueSyncedPlaylists, lastSyncedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncedPlaylist
	for rows.Next() {
		var i SyncedPlaylist
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Name,
			&i.CoverUrl,
			&i.TracksJson,
			&i.SyncEnabled,
			&i.SyncIntervalSec,
			&i.AutoDownload,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncedPlaylists = `-- name: ListSyncedPlaylists :many
SELECT id, source, external_id, name, cover_url, tracks_json, sync_enabled, sync_interval_sec, auto_download, last_synced_at, created_at FROM synced_playlists ORDER BY created_at DESC
`

func (q *Queries) ListSyncedPlaylists(ctx context.Context) ([]SyncedPlaylist, error) {
	rows, err := q.db.QueryContext(ctx, listSyncedPlaylists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncedPlaylist
	for rows.Next() {
		var i SyncedPlaylist
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Name,
			&i.CoverUrl,
			&i.TracksJson,
			&i.SyncEnabled,
			&i.SyncIntervalSec,
			&i.AutoDownload,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSyncedPlaylistSettings = `-- name: UpdateSyncedPlaylistSettings :exec
UPDATE synced_playlists SET sync_enabled = ?, sync_interval_sec = ?, auto_download = ? WHERE id = ?
`

type UpdateSyncedPlaylistSettingsParams struct {
	SyncEnabled     int64  `json:"sync_enabled"`
	SyncIntervalSec int64  `json:"sync_interval_sec"`
	AutoDownload    int64  `json:"auto_download"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateSyncedPlaylistSettings(ctx context.Context, arg UpdateSyncedPlaylistSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSyncedPlaylistSettings,
		arg.SyncEnabled,
		arg.SyncIntervalSec,
		arg.AutoDownload,
		arg.ID,
	)
	return err
}

const updateSyncedPlaylistTracks = `-- name: UpdateSyncedPlaylistTracks :exec
UPDATE synced_playlists SET name = ?, cover_url = ?, tracks_json = ?, last_synced_at = ? WHERE id = ?
`

type UpdateSyncedPlaylistTracksParams struct {
	Name         string `json:"name"`
	CoverUrl     string `json:"cover_url"`
	TracksJson   string `json:"tracks_json"`
	LastSyncedAt int64  `json:"last_synced_at"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateSyncedPlaylistTracks(ctx context.Context, arg UpdateSyncedPlaylistTracksParams) error {
	_, err := q.db.ExecContext(ctx, updateSyncedPlaylistTracks,
		arg.Name,
		arg.CoverUrl,
		arg.TracksJson,
		arg.LastSyncedAt,
		arg.ID,
	)
	return err
}

const upsertSyncedPlaylist = `-- name: UpsertSyncedPlaylist :one
INSERT INTO synced_playlists (id, source, external_id, name, cover_url, tracks_json, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(source, external_id) DO UPDATE SET
  name = excluded.name, cover_url = excluded.cover_url, tracks_json = excluded.tracks_json
RETURNING id, source, external_id, name, cover_url, tracks_json, sync_enabled, sync_interval_sec, auto_download, last_synced_at, created_at
`

type UpsertSyncedPlaylistParams struct {
	ID         string `json:"id"`
	Source     string `json:"source"`
	ExternalID string `json:"external_id"`
	Name       string `json:"name"`
	CoverUrl   string `json:"cover_url"`
	TracksJson string `json:"tracks_json"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) UpsertSyncedPlaylist(ctx context.Context, arg UpsertSyncedPlaylistParams) (SyncedPlaylist, error) {
	row := q.db.QueryRowContext(ctx, upsertSyncedPlaylist,
		arg.ID,
		arg.Source,
		arg.ExternalID,
		arg.Name,
		arg.CoverUrl,
		arg.TracksJson,
		arg.CreatedAt,
	)
	var i SyncedPlaylist
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Name,
		&i.CoverUrl,
		&i.TracksJson,
		&i.SyncEnabled,
		&i.SyncIntervalSec,
		&i.AutoDownload,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}
