// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, password_hash, role_id, is_owner) VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	RoleID       string `json:"role_id"`
	IsOwner      int64  `json:"is_owner"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.RoleID,
		arg.IsOwner,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, role_id, is_owner, disabled, created_at, updated_at, last_seen FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsOwner,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeen,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role_id, is_owner, disabled, created_at, updated_at, last_seen FROM users WHERE username = ? COLLATE NOCASE
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsOwner,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeen,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, role_id, is_owner, disabled, created_at, updated_at, last_seen FROM users ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.RoleID,
			&i.IsOwner,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserDisabled = `-- name: SetUserDisabled :exec
UPDATE users SET disabled = ?, updated_at = unixepoch() WHERE id = ?
`

type SetUserDisabledParams struct {
	Disabled int64  `json:"disabled"`
	ID       string `json:"id"`
}

func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error {
	_, err := q.db.ExecContext(ctx, setUserDisabled, arg.Disabled, arg.ID)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = ?, updated_at = unixepoch() WHERE id = ?
`

type SetUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           string `json:"id"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const touchUserLastSeen = `-- name: TouchUserLastSeen :exec
UPDATE users SET last_seen = unixepoch() WHERE id = ?
`

func (q *Queries) TouchUserLastSeen(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchUserLastSeen, id)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role_id = ?, updated_at = unixepoch() WHERE id = ?
`

type UpdateUserRoleParams struct {
	RoleID string `json:"role_id"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.RoleID, arg.ID)
	return err
}
